DROP TABLE IF EXISTS BOARD;
DROP SEQUENCE IF EXISTS BOARD_SEQ;

CREATE SEQUENCE BOARD_SEQ;
CREATE TABLE BOARD
(
  BOARD_ID BIGINT DEFAULT BOARD_SEQ.nextval PRIMARY KEY NOT NULL,
  TITLE    VARCHAR(100)
);

