DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD (
  board_id INTEGER PRIMARY KEY AUTOINCREMENT,
  title    VARCHAR(100)
);

DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
  category_id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100)
);